## Deliverable 2. Create a Customer Travel Destinations Map.

In [11]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [12]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("weather_data/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Saint-Gaudens,FR,43.0833,0.6667,56.01,94,100,2.62,overcast clouds,2022-06-28 03:50:01
1,1,Nang Rong,TH,14.6377,102.7914,91.29,50,32,7.67,scattered clouds,2022-06-28 03:50:02
2,2,Busselton,AU,-33.6500,115.3333,59.58,55,87,8.28,overcast clouds,2022-06-28 03:50:03
3,3,High Level,CA,58.5169,-117.1360,64.51,48,20,6.91,few clouds,2022-06-28 03:45:03
4,4,Robat Karim,IR,35.4846,51.0829,89.46,23,0,13.80,clear sky,2022-06-28 03:50:04

In [13]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
city_data_df = pd.read_csv("weather_Data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Gamba,GA,-2.6500,10.0000,69.10,95,95,5.10,overcast clouds,2022-06-28 03:57:12
1,1,Kavaratti,IN,10.5669,72.6420,81.95,80,100,21.14,overcast clouds,2022-06-28 03:53:20
2,2,Viedma,AR,-40.8135,-62.9967,45.59,52,86,3.94,overcast clouds,2022-06-28 03:57:13
3,3,Vaini,TO,-21.2000,-175.2000,78.96,69,20,10.36,few clouds,2022-06-28 03:50:54
4,4,Puerto Escondido,MX,15.8500,-97.0667,79.83,82,51,3.74,broken clouds,2022-06-28 03:50:19

In [14]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

In [15]:
# 4a. Determine if there are any empty rows.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Gamba,GA,-2.6500,10.0000,69.10,95,95,5.10,overcast clouds,2022-06-28 03:57:12
1,1,Kavaratti,IN,10.5669,72.6420,81.95,80,100,21.14,overcast clouds,2022-06-28 03:53:20
3,3,Vaini,TO,-21.2000,-175.2000,78.96,69,20,10.36,few clouds,2022-06-28 03:50:54
4,4,Puerto Escondido,MX,15.8500,-97.0667,79.83,82,51,3.74,broken clouds,2022-06-28 03:50:19
6,6,Acapulco,MX,16.8634,-99.8901,80.42,83,100,9.22,overcast clouds,2022-06-28 03:48:12
7,7,Fortuna,US,40.5982,-124.1573,57.92,85,22,4.00,few clouds,2022-06-28 03:50:44
8,8,Jamestown,US,42.0970,-79.2353,62.19,67,100,4.61,overcast clouds,2022-06-28 03:50:32
9,9,Atuona,PF,-9.8000,-139.0333,77.67,79,19,18.14,light rain,2022-06-28 03:50:22
10,10,Lorengau,PG,-2.0226,147.2712,85.48,65,38,9.91,scattered clouds,2022-06-28 03:57:14
12,12,Khandyga,RU,62.6667,135.6000,72.93,75,95,8.84,light rain,2022-06-28 03:51:52

In [16]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df.count()

City_ID                609
City                   609
Country                609
Lat                    609
Lng                    609
Max Temp               609
Humidity               609
Cloudiness             609
Wind Speed             609
Current Description    609
Date                   609
dtype: int64

In [17]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Gamba,GA,69.10,overcast clouds,-2.6500,10.0000,
1,Kavaratti,IN,81.95,overcast clouds,10.5669,72.6420,
3,Vaini,TO,78.96,few clouds,-21.2000,-175.2000,
4,Puerto Escondido,MX,79.83,broken clouds,15.8500,-97.0667,
6,Acapulco,MX,80.42,overcast clouds,16.8634,-99.8901,
7,Fortuna,US,57.92,few clouds,40.5982,-124.1573,
8,Jamestown,US,62.19,overcast clouds,42.0970,-79.2353,
9,Atuona,PF,77.67,light rain,-9.8000,-139.0333,
10,Lorengau,PG,85.48,scattered clouds,-2.0226,147.2712,
12,Khandyga,RU,72.93,light rain,62.6667,135.6000,

In [9]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, hotel in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = hotel["Lat"]
    lng = hotel["Lng"]
    params["location"]= f'{lat},{lng}'
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df.count()

City                   609
Country                609
Max Temp               609
Current Description    609
Lat                    609
Lng                    609
Hotel Name             609
dtype: int64

In [18]:
# 8a. Create the output File (CSV)
output_data_file = "weather_data/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [19]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current description</dt><dd>{Current Description}</dd>
</dl>

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [20]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))