## Deliverable 3. Create a Travel Itinerary Map.

In [58]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [59]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("weather_data/WeatherPy_vacation.csv")
vacation_df.head(30)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Gamba,GA,69.10,overcast clouds,-2.6500,10.0000,NaN
1,1,Kavaratti,IN,81.95,overcast clouds,10.5669,72.6420,Hotels in Lakshadweep Islands
2,3,Vaini,TO,78.96,few clouds,-21.2000,-175.2000,Keleti Beach Resort
3,4,Puerto Escondido,MX,79.83,broken clouds,15.8500,-97.0667,Aldea del Bazar Hotel and Spa
4,6,Acapulco,MX,80.42,overcast clouds,16.8634,-99.8901,HS Hotsson Smart Acapulco
5,7,Fortuna,US,57.92,few clouds,40.5982,-124.1573,Super 8 by Wyndham Fortuna
6,8,Jamestown,US,62.19,overcast clouds,42.0970,-79.2353,Hampton Inn & Suites Jamestown
7,9,Atuona,PF,77.67,light rain,-9.8000,-139.0333,Villa Enata
8,10,Lorengau,PG,85.48,scattered clouds,-2.0226,147.2712,Lorengau Harbourside Hotel
9,12,Khandyga,RU,72.93,light rain,62.6667,135.6000,Apel'sin
10,13,Hobart,AU,58.26,light rain,-42.8794,147.3294,St Ives Hobart Accommodation Tasmania
11,14,Yar-Sale,RU,52.77,overcast clouds,66.8333,70.8333,Yalemd
12,15,Souillac,MU,70.18,scattered clouds,-20.5167,57.5167,Shanti Maurice Resort & Spa
13,16,Bandundu,CD,72.21,scattered clouds,-3.3167,17.3667,Coja Color
14,17,Astoria,US,58.93,few clouds,46.1879,-123.8313,Best Western Astoria Bayfront Hotel
15,18,Rikitea,PF,73.56,few clouds,-23.1203,-134.9692,People ThankYou
16,19,Georgetown,MY,87.75,few clouds,5.4112,100.3354,Cititel Penang
17,20,Dingle,PH,84.65,heavy intensity rain,10.9995,122.6711,SEGAYA PROPERTY
18,21,Buala,SB,82.35,light rain,-8.1450,159.5921,Maringe Lagoon Lodge
19,22,Albany,US,63.01,clear sky,42.6001,-73.9662,NaN
20,23,Yellowknife,CA,61.32,few clouds,62.4560,-114.3525,The Explorer Hotel
21,25,Bambanglipuro,ID,82.51,overcast clouds,-7.9500,110.2833,Puri Brata
22,26,New Norfolk,AU,58.91,moderate rain,-42.7826,147.0587,The Shingles Riverside Cottages
23,27,East London,ZA,56.07,clear sky,-33.0153,27.9116,Tu Casa
24,28,Bairiki,KI,84.20,light rain,1.3292,172.9752,Tarawa Boutique Hotel
25,29,Willemstad,CW,80.51,few clouds,12.1084,-68.9335,Avila Beach Hotel
26,30,Ampanihy,MG,55.15,clear sky,-24.7000,44.7500,Angora Hotel
27,31,Mendota,US,89.73,clear sky,36.7536,-120.3816,Joe Gómez motel
28,32,Busselton,AU,59.58,overcast clouds,-33.6500,115.3333,Observatory Guest House
29,36,Barrow,US,51.82,overcast clouds,71.2906,-156.7887,King Eider Inn

In [60]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current description</dt><dd>{Current Description}</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [69]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [66]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.
vacation_start = "Haverhill"
vacation_end = "Haverhill"
city2 = "Palmer"
city3 = "Bethel"
city4 = "Westport"

vacation_start = vacation_df.loc[vacation_df["City"] == vacation_start]
vacation_end = vacation_df.loc[vacation_df["City"] == vacation_end]  
vacation_stop2 = vacation_df.loc[vacation_df["City"] == city2]
vacation_stop3 = vacation_df.loc[vacation_df["City"] == city3] 
vacation_stop4 = vacation_df.loc[vacation_df["City"] == city4]

In [70]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()[0]
end = vacation_end[["Lat", "Lng"]].to_numpy()[0]
stop1 = vacation_stop2[["Lat", "Lng"]].to_numpy()[0]
stop2 = vacation_stop3[["Lat", "Lng"]].to_numpy()[0]
stop3 = vacation_stop4[["Lat", "Lng"]].to_numpy()[0]

In [71]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
travel_route = gmaps.directions_layer(start, end, waypoints=[stop1,stop2,stop3], travel_mode="DRIVING" or "BICYCLING" or "WALKING")
fig.add_layer(travel_route)
fig

Figure(layout=FigureLayout(height='420px'))

In [72]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop2,vacation_stop3,vacation_stop4],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,172,Haverhill,US,71.51,overcast clouds,42.7762,-71.0773,Best Western Merrimack Valley
1,457,Palmer,US,67.55,scattered clouds,42.1584,-72.3287,Wedgewood Motel
2,114,Bethel,US,68.36,clear sky,41.3712,-73.4140,Courtyard by Marriott Danbury
3,440,Westport,US,70.77,overcast clouds,41.1415,-73.3579,The Westport Inn

In [73]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [74]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))